version: "2"

services:
  postgres:
    restart: always
    image: postgres:9.4
    networks:
      - projectsecure

  api:
    restart: always
    image: nikriek/projectsecure-api:latest
    networks:
      - projectsecure
    depends_on:
      - postgres
    links:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: projectsecure.settings
    env_file:
      - projectsecure-production.env
    networks:
      - projectsecure

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - client
    links:
      - api
      - client
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=www.projectsecure.org
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - projectsecure

  client:
    restart: always
    build: https://github.com/projectsecure/client.git
    environment:
      PORT: 4000
      HOST: "www.projectsecure.org"
    networks:
      - projectsecure

networks:
  projectsecure:
